### ISSUE TITLE
select dropdown list resize issue

### ISSUE THREAD

**Issue by Hatead1** [retejs/vue-render-plugin#10]
https://codepen.io/hatead1/pen/aXgjQp?editors=0110

Zoom view, look at dropdown font size at the different scale.
Когда меняется масштаб экрана, не меняется размер фонта выпадающего списка.

**Comment by Ni55aN** [comment]
Нативный селект так и ведет себя при `transform: scale`. Лучше тогда использовать кастомный select

**Comment by Hatead1** [comment]
Жаль, лишнее усложнение.

**Comment by Hatead1** [comment]
Виталий, а как тогда подцепить что-то типа https://vuejsexamples.com/a-highly-dynamic-vue-dropdown-component/ ?

**Comment by Ni55aN** [comment]
Достаточно передать VueDropdown в component свойство класса, который расширяет Rete.Control

```js
class SelectControl extends Rete.Control {

  constructor(emitter, key) {
    super(key);
    this.component = VueDropdown;
    this.props = {
        config: {
            options: [
                {
                    value: "option 1"
                },
                {
                    value: "option 2"
                },
                {
                    value: "option 3"
                },
            ],
            prefix: "The",
            backgroundColor: "green"
        },
        setSelectedOption(e) { console.log('Selected', e) }
     };
  }
}
```

**Comment by Hatead1** [comment]
сделал npm i ...., компонент появился в списке зависимостей, но что-то не пойму, как его (VueDropdown) объявить? На import ругается, на require тоже.

**Comment by Hatead1** [comment]
Спасибо, разобрался.
