### ISSUE TITLE
_vm.socket is undefined

### ISSUE THREAD

**Issue by wjalmuzndmcs** [retejs/vue-render-plugin#11]
Hi  !

I'm trying to set up simple webpage with nodeEditor using Vue ( to which I'm complete beginner). I have set-up some app using examples from rete.js.org in which nodeEditor is created inside Vue component. In principle editor works and I can create Num nodes, but the sockets are missing. Console shows an error:
 
```
[Vue warn]: Error in render: "TypeError: _vm.socket is undefined"

found in

---> <Socket>
       <Anonymous>
         <Root>
```
I know it is not much info to replicate the problem, but maybe someone more experienced will exactly know what happens - I looked through all resources and found no clues :( especially that when I start app from rete.js.org repo editors are working fine. 

Best,

**Comment by Ni55aN** [comment]
> I know it is not much info to replicate the problem

Exactly, you need to share the code you changed and call stack.

**Comment by wjalmuzndmcs** [comment]
Hello, 

I'm attaching the callstack and source files - it was scaffolded using vue-cli. When you open webpage functioning editor is on purple part of the window. 
 
[my-project.zip](https://github.com/retejs/vue-render-plugin/files/3185445/my-project.zip)
[callstack.txt](https://github.com/retejs/vue-render-plugin/files/3185446/callstack.txt)

Best regards.

**Comment by wjalmuzndmcs** [comment]
I've just realized call stack from previous post had some folded entries - belowe there is a full one:

[callstack.txt](https://github.com/retejs/vue-render-plugin/files/3185481/callstack.txt)

**Comment by Ni55aN** [comment]
Try to use Vue CLI. Perhaps the problem in webpack configs

**Comment by Ni55aN** [comment]
I got error `Error in render: "TypeError: Cannot read property 'name' of undefined"`

**Comment by Ni55aN** [comment]
There s a wrong arguments
```js
let out = new Rete.Output('Number', numSocket)
```
Correct:

```js
let out = new Rete.Output('num', 'Number', numSocket)
```

**Comment by wjalmuzndmcs** [comment]
I feel very stupid :( I do not know how it happened. Anyway thank you very much for your help and maybe in some time I can contribute to the project :)
