### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by HendrikRoth** [retejs/vue-render-plugin#13]
I am not able to use vue-render-plugin. Am i doing something wrong?

Project example: (components/Editor/Editor.vue)

https://codesandbox.io/s/rete-test-cehn8

**Comment by Ni55aN** [comment]
You need to import polyfill manually or use babel (depends on your build system)

**Comment by Ni55aN** [comment]
https://github.com/retejs/rete/issues/247
