### ISSUE TITLE
How i can use v-tooltip ? May you give some instruction?

### ISSUE THREAD

**Issue by rensingh-1983** [retejs/vue-render-plugin#15]

**Comment by Ni55aN** [comment]
What library is this directive from?

**Comment by rensingh-1983** [comment]
I have cloned the repo and doing change in node.vue. At one place i need to add v-tooltip to show description of node and output input socket.

**Comment by Ni55aN** [comment]
Did you clone the whole repo? Are you going to build the fork for yourself?

**Comment by rensingh-1983** [comment]
Yes I wan to build the fork for myself? But I am unable to use v-tooltip.

**Comment by Ni55aN** [comment]
I am wondering what is the sense of `v-app`, it adds extra styles

**Comment by Ni55aN** [comment]
https://github.com/retejs/vue-render-plugin/issues/14#issuecomment-535591956
