### ISSUE TITLE
Add support for router 

### ISSUE THREAD

**Issue by andrey-zakharov** [retejs/vue-render-plugin#16]
App's router does not pass into new Vue instance.

**Comment by Ni55aN** [comment]
Why the plugin should do it?

**Comment by andrey-zakharov** [comment]
it creates Vue instances. In ctor of Vue component instance, there is option 'router'. It neither not accessible from outside, nor filled by plugin. 
So, it could be solved by bypassing additional obj for Vue ctor internal call here:
```
function createVue(el, vueComponent, vueProps) {
    const app = new Vue({
        render: h => h(vueComponent, { props: vueProps })
    });

```

**Comment by Ni55aN** [comment]
Still cant understand the sense of accessing the router directly from the nodes, since each Node istance have isolated UI (Vue instance)

**Comment by andrey-zakharov** [comment]
to make links to other views, for example to children of this nodes like
```<router-link :to="{ name: 'view', params: { rootId: node.data.id }}"></router-link>```

but `:to` would not work without `this.$router`

**Comment by Ni55aN** [comment]
Instead of tightly coupling your application with a nodes, you should to emit events from your nodes. For example: 

```js
this.data.props = { goto: pushRoute };
```

```vue
<template>
  <a @click="goto({ name: 'view', params: { rootId: node.data.id }})">
</template>
```

**Comment by Ni55aN** [comment]
In `v0.5.0` you can [pass the router to instances](https://github.com/retejs/vue-render-plugin/issues/17#issuecomment-535591609)
