### ISSUE TITLE
Add support for Vue plugins

### ISSUE THREAD

**Issue by cvisl** [retejs/vue-render-plugin#17]
Now all the components within retejs vue-render-plugin are rendered separately as their own vue instances. This disables the option to have a global Vuex store for example, maybe for now it can be imported per component, I don't know.

It would be useful in general to be able to globally define the Vue plugins in the options for example to use them over all components created throughout rete.

**Comment by Ni55aN** [comment]
`v0.5.0`
```js
editor.use(VueRenderPlugin, {
    options: {
        // router, plugin, etc.
    }
});
```

**Comment by mstrouhal** [comment]
It is working great now, thank you!

**Comment by Relatora** [comment]
can you please point me out to a working example. I'm new to Vue and would like to use Retejs for a project.

**Comment by Ni55aN** [comment]
@Relatora do you want to integrate this into an existing project or create a new one?

**Comment by Relatora** [comment]
I'm creating a new project

**Comment by cvisl** [comment]
@Relatora For me its working now and I am using it like this:

Define the store in e.g. ./store/index.ts.
```
import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
    plugins: [],
    modules:{
    },
    state:{
    },
    mutations: {
    },
    actions: {
    },
    strict: false
})
```

And where ever you define the vuerenderplugin import it into Rete.js like this:
```
import store from '../store'

this.editor.use(VueRenderPlugin, {
        options: {
            store
        }
      });
```
Hope this is of some help to you.
