### ISSUE TITLE
Popup a modal form when node is double-clicked

### ISSUE THREAD

**Issue by Relatora** [retejs/vue-render-plugin#19]
Hi, I'd like to Popup a modal form when a node is double-clicked. Then pass form payload back to the node. Can you show me how to do it on Vue? Thanks!

**Comment by Ni55aN** [comment]
```js
editor.on('rendernode', ({ el, node }) => el.addEventListener('dblclick', () => {
  // open modal. There are many ways, it depends on your modal impelementation
  // send data to `node`
}));
```

**Comment by Relatora** [comment]
Thanks for your response, I figured triggering double click but the part of loading the model form and getting it's payload and feeding it to the node is the part that alludes me. If you can point me out to some code that achieves this it would be appreciated. All the rete code is on editor.js file separated from the vue component. Can this be implemented from the js file or do I have to import it to my vue component and manipulated from there?

**Comment by Ni55aN** [comment]
I think you should determine where your modal should be visualized, and open it with something like an event bus.

For example, put a modal outside of the editor's area, bind an event in the editor (`editor.bind('openmodal')), trigger `openmodal` event by dblclick and listen this event where modal added
