### ISSUE TITLE
It is not working with 

### ISSUE THREAD

**Issue by dev-yaris** [retejs/vue-render-plugin#21]
- rete v1.4.2
- rete-vue-render-plugin v0.5.0  

https://codepen.io/Ni55aN/pen/EGZOdK

Could you provide examples of the following components?
import CustomNodeComponent from './CustomNodeComponent.vue';
import CustomControlComponent from './CustomControlComponent.vue';

![image](https://user-images.githubusercontent.com/61779545/76627654-0ee08c80-6544-11ea-8611-dbbc9ed672f1.png)

```
var CustomNode = {
    template: `<div class="node" :class="[selected(), node.name] | kebab">
  <!--- hide title <div class="title">{{node.name}}</div> -->
  <!-- Outputs-->
  <div class="output" v-for="output in outputs()" :key="output.key">
    <div class="output-title">{{output.name}}</div>
    <Socket v-socket:output="output" type="output" :socket="output.socket"></Socket>
  </div>
  <!-- Controls-->
  <div class="control" v-for="control in controls()" v-control="control"></div>
  <!-- Inputs-->
  <div class="input" v-for="input in inputs()" :key="input.key">
    <Socket v-socket:input="input" type="input" :socket="input.socket"></Socket>
    <div class="input-title" v-show="!input.showControl()">{{input.name}}</div>
    <div class="input-control" v-show="input.showControl()" v-control="input.control"></div>
  </div>
</div>`,
    mixins: [VueRenderPlugin.mixin],
    components: {
        Socket: VueRenderPlugin.Socket
    }
}
```

```
editor.use(VueRenderPlugin, {
    component: CustomNode
});
```

**Comment by Ni55aN** [comment]
What `CustomNodeComponent.vue` do you mean? The example on Codepen has runtime compiled component

**Comment by dev-yaris** [comment]
When I use that component it renders following code 

`<!-- function ... -->`

but expected valid html of a node

**Comment by Ni55aN** [comment]
I think the problem is the different versions of Vue used in the plugin and your application. What version of Vue are you using in your application?
