### ISSUE TITLE
Use Custom Node HTML with latest version

### ISSUE THREAD

**Issue by Mukatai** [retejs/vue-render-plugin#28]
Hello,

I try to use this 2 exemples with latest versions of rete.js et vue-render-plugin : 

[https://codepen.io/Ni55aN/pen/EGZOdK](https://codepen.io/Ni55aN/pen/EGZOdK)
[https://codepen.io/Ni55aN/pen/GGrzYE](https://codepen.io/Ni55aN/pen/GGrzYE)

But its not work if i change the version of vue-render-plugin (0.2.6 to 0.5.0) .

In codepen.io exemple (Rete.js Node Editor UE4 Style) i change just the version of rete.js and vue-render-plugin in Add External Scripts/Pens : 
https://cdn.jsdelivr.net/npm/rete-vue-render-plugin@0.2.6/build/vue-render-plugin.min.js
to
https://cdn.jsdelivr.net/npm/rete-vue-render-plugin@0.5.0/build/vue-render-plugin.min.js

https://cdn.jsdelivr.net/npm/rete@1.2.2/build/rete.min.js
to
https://cdn.jsdelivr.net/npm/rete@1.4.4/build/rete.min.js

and change :
editor.use(VueRenderPlugin); 
to 
editor.use(VueRenderPlugin.default); 
(line 121) 

After that i have this error : 
TypeError: Cannot read property 'props' of undefined

If i add in the constructor these lines it's the same result :
`class AddComponent extends Rete.Component {`
`    constructor(){`
`        super("Add");`
`        this.data.render = 'vue';`
`        this.data.component = CustomNode;`
`        this.data.props = {};`
`    }`
`...`

I want use custom node with pure html, js and css. And this exemples are perfect for me. 

Can you help me for use the latest version of vue-render-plugin with html template ? Why i have this error ?

Thanks.
@+

**Comment by Mukatai** [comment]
After use vue.js in development mode i found the problem.

The CustomNode declaration  must be : 

```
var CustomNode = {
template:'....',
mixins: [VueRenderPlugin.default.mixin],
components: {
    Socket: VueRenderPlugin.default.Socket
  }
}
```

**Comment by ghost** [comment]
> After use vue.js in development mode i found the problem.
> 
> The CustomNode declaration must be :
> 
> ```
> var CustomNode = {
> template:'....',
> mixins: [VueRenderPlugin.default.mixin],
> components: {
>     Socket: VueRenderPlugin.default.Socket
>   }
> }
> ```

thankyou
