### ISSUE TITLE
socket.hint - ?

### ISSUE THREAD

**Issue by Hatead1** [retejs/vue-render-plugin#3]
In socket.vue

:title="socket.name+'\\n'+socket.hint" - always undefined 
Зачем нужна эта переменная, она нигде не объявляется и не используется.

**Comment by Ni55aN** [comment]
It was removed in rete@1.0.0, so the `hint` property isn't defined for socket. I'll remove it in the nearest time (or Pull Request welcome)

**Comment by Hatead1** [comment]
pull req later. 
Надо потренироваться :)
