### ISSUE TITLE
Bootstrap-vue-3 and vue-render-plugin

### ISSUE THREAD

**Issue by dimball** [retejs/vue-render-plugin#49]
Hi

I have been trying to use bootstrap-vue-3 and Retejs (latest version), with Vite. And while I can get to render the nodes (yay) and most of the system, I cannot get it to render the controls when using with bootstrap-vue-3 npm package. 

I looked into the source code of the vue-render-plugin, and I am just theorising if each of the apps (from the createapp method) needs to use a ".use(boostrapvue3)" in them in order for the app to know to use bootstrap-vue-3. At the moment, it cannot resolve the components used in bootstrap vue 3 at all, and just renders the controls as pure text. 

So my question is, is my theory in the right direction? And if so, I tried to build the plugin, but i get a bunch of errors (about it cannot import the dependencies, because of not recognising this as modules etc). I even tried to follow the rete CLI documentation, and that also gave me a bunch of errors. I am using nodejs version 16. 

Is the rete CLI documentation still correct for creating a new plugin and building it? does it still work for other people doing the same steps? 

[https://rete.js.org/#/cli#lang=en&tosearch=r]

**edit:**

_I got it to work, but there was a missing part in the vue-render-plugin which did not do anything with the passed in options. I.e I could not do a "use([my passed in plugin])" for the vue app in the createcontrol method. I added that section to do this with the passed in options, and it could display bootstrap-vue-3 nicely._

I could still not get the rete CLI to work, but I am using a modified local version of the vue-render-plugin instead, which gives me what I need at the moment.

**Comment by boehmrn** [comment]
Any updates @dimball @Ni55aN ? I cannot figure out how to make the plugin use the "options" parameter. I am struggling to use Quasar components. 
Thanks for helping in advance
