### ISSUE TITLE
area.update doesn't work

### ISSUE THREAD

**Issue by jangxx** [retejs/vue-render-plugin#62]
I'm trying to build a node which can dynamically update and remove outputs. According to the documentation this should be possible by simply calling `addOutput` and `removeOutput`, followed by a call to `area.update("node", node.id)`, but this does not work. The outputs on the node never change.

Library versions used:

```
"rete": "^2.0.0-beta.6",
"rete-area-plugin": "^2.0.0-beta.9",
"rete-connection-plugin": "^2.0.0-beta.9",
"rete-context-menu-plugin": "^2.0.0-beta.6",
"rete-engine": "^2.0.0-beta.7",
"rete-render-utils": "^2.0.0-beta.9",
"rete-vue-render-plugin": "^2.0.0-beta.11",
"vue": "^3.2.47",
```

**Comment by Ni55aN** [comment]
fixed in 2.0.0-beta.12

**Comment by jangxx** [comment]
Thanks for the quick reply! Looking forward to trying it out tomorrow.

**Comment by jangxx** [comment]
Tried it, and it works great. Thanks again!
