### ISSUE TITLE
rendering of data and emit tag as string to html

### ISSUE THREAD

**Issue by agentschmitt** [retejs/vue-render-plugin#78]
It seems the vue plugin renders some incorect stuff to the html markup.
For custom control it renders some emit and data tags with some strange text.
For input and output node it is the same.

This issue only happens with versions from 2.0.1 to 2.0.4. In version 2.0.0 their was no such issue.

```
<div data-v-cc6bc301="" emit="function () { [native code] }" data="[object Object]" class="control" data-testid="control-input" data-v-app="">
   <input data-v-a4adbbb3="" type="number" seed="0.22975907885377467">
</div>
```

```
<div data-v-cc6bc301="" class="output" data-testid="output-a">
   <div data-v-cc6bc301="" class="output-title" data-testid="output-title"></div>
   <div data-v-cc6bc301="" data="[object Object]" emit="function () { [native code] }" class="output-socket" data-testid="output-socket" data-v-app="">
      <div data-v-4a0a4b7f="" class="socket" title="socket" seed="0.9482170948208757"></div>
   </div>
</div>
```

example with vue-plugin@2.0.4 (reproduces the bug with rendering the data and emit attributes)
https://codesandbox.io/s/rete-js-v2-vue-js-custom-controls-forked-ny25jg

example with vue-plugin@2.0.0 (without bug, official example: https://retejs.org/examples/controls/vue)
https://codesandbox.io/s/rete-js-v2-vue-js-custom-controls-qrdo2c?from-embed

**Comment by devRoemer** [comment]
Might have been brought in with: https://github.com/retejs/vue-plugin/commit/437565be46cf906d74783d2508815b377ef0c759#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80

**Comment by Ni55aN** [comment]
> . In version 2.0.0 their was no such issue

because v2.0.0 doesn't use reusable Ref component (it has another issue related to memory leak). Hmm.. at the same time, 2.0.1+ uses Ref for classic preset and doesn't produce these attribute "interpolations".

Do you think it affects the functionality/stability of your application?

**Comment by devRoemer** [comment]
From our point of view it's just a minor imperfection. We did not notice any impact on the application regarding stability or performance.

I think it's related to
`div(v-bind="$props" ref="element")`
from the referenced commit, where $props is bound. There only other fields, except data and emit should be bound. I am not sure if it's worth a change or if it's to risky.
