### ISSUE TITLE
Click event doesn't fire inside custom components for vue renderer plugin

### ISSUE THREAD

**Issue by dlohvinov** [retejs/vue-render-plugin#84]
Вітаю!

I'm having an issue using `@click` event subscribers on components or html elements inside components, which are passed to vue renderer to override default appearance.

`click` event is just not firing. However, `mousedown` is.

It can be reproduced using html button in [docs example](https://retejs.org/examples/customization/vue).

```html
<button type="button" @click="handleClick" @mousedown="handleClick">click me!</button>
 ```
and
```javascript
    handleClick() {
      alert('click!');
    },
```

Is it a bug, or it was made purposely and should I try to find a workaround here?

Дякую! ❤️

**Comment by Ni55aN** [comment]
Вітаю!

It requires `@pointerdown.stop=""` in order to prevent dragging (which prevents click/dblclick)

https://retejs.org/docs/guides/renderers/vue#controls

**Comment by dlohvinov** [comment]
O, that's it, thank you so much! ❤️

**Comment by dlohvinov** [comment]
@Ni55aN , вітаю!

Your response helped me to solve the issue, but now i'm stuck with another one:

1. if add a `<button>` element to my `custom-node.vue`, and click on it - it works as expected - selects the node :)
2. But if i do the same but with `@pointerdown.stop` (node is not selected and not dragged (as expected, too), BUT!, my event listener doesn't fire: `@click`/`@mousedown` - both of them does not work :(

Maybe i'm missing something when i'm trying to use a button in my custrom node like that?

**Comment by dlohvinov** [comment]
> It can be reproduced using html button in [docs example](https://retejs.org/examples/customization/vue).
> 
> ```
> <button type="button" @click="handleClick" @mousedown="handleClick">click me!</button>
> ```
> 
> and
> 
> ```js
>     handleClick() {
>       alert('click!');
>     },
> ```

seems to me, this reproduction is relevant :(
