### ISSUE TITLE
Missing .d.ts

### ISSUE THREAD

**Issue by andrey-zakharov** [retejs/vue-render-plugin#9]
Trying to use it with typescript and compiler gives error:
```
Could not find a declaration file for module 'rete-vue-render-plugin'.
```
.

**Comment by Ni55aN** [comment]
Is this an error or warning? If it's error, you can create `index.d.ts` with the next content

```
declare const _default: {
    name: string,
    install: Function,
    mixin: any,
    Node: any,
    Socket: any
};
export default _default;
```

**Comment by Ni55aN** [comment]
https://github.com/Microsoft/TypeScript/issues/15031#issuecomment-291957621
